# Generated by Django 5.2 on 2025-05-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BildMitBeschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='bilder/')),
                ('beschreibung', models.TextField()),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
